# docs/_config.yml
title: Meu Catálogo de Produtos
description: Site da Drogaria Santa Maria Pinheirinho
theme: jekyll-theme-primer
markdown: kramdown

# Configurações específicas para Jekyll
source: docs
destination: docs/_site

# Excluir a pasta _site do repositório
exclude:
  - "_site"

# Permitir Sass (SCSS)
sass:
  style: compressed

# Definir as variáveis de CSS
sass_dir: "assets/css"
